web-juridico-webapp/src/main/java/br/com/juridico/controller/AgendaGeralController.java
package br.com.juridico.controller;

import br.com.juridico.business.AgendaEmailBusiness;
import br.com.juridico.business.EmailTemplateBusiness;
import br.com.juridico.business.TipoAndamentoBusiness;
import br.com.juridico.dto.PessoaAgendaDto;
import br.com.juridico.entidades.*;
import br.com.juridico.enums.ControladoriaIndicador;
import br.com.juridico.enums.TipoOperacaoIndicador;
import br.com.juridico.exception.ValidationException;
import br.com.juridico.impl.*;
import br.com.juridico.state.ControladoriaState;
import br.com.juridico.state.controladoria.AprovaControladoria;
import br.com.juridico.state.controladoria.ControladoriaContext;
import com.google.common.base.Strings;
import com.google.common.collect.Lists;
import com.google.common.collect.Maps;
import org.apache.log4j.Logger;
import org.primefaces.context.RequestContext;
import org.primefaces.event.SelectEvent;
import org.primefaces.model.DefaultScheduleEvent;
import org.primefaces.model.LazyScheduleModel;
import org.primefaces.model.ScheduleEvent;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.event.ActionEvent;
import javax.faces.event.ValueChangeEvent;
import javax.inject.Inject;
import java.io.Serializable;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;

/**
 * Created by Jefferson on 23/08/2016.
 */
@ManagedBean
@ViewScoped
public class AgendaGeralController extends AbstractAgendaController implements Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -7613942626769610539L;
	private static final Logger LOGGER = Logger.getLogger(AgendaGeralController.class);
	private static final String TODOS = "Todos";
	private static final String INDEFINIDO = "Indefinido";
	private static final String PESSOA_SELECT_FLASH = "PESSOA_SELECT_FLASH";
	private static final String CHAVE_ACESSO = "GERAL_AGENDA_GERAL_FORM";
	private static final String TRANSFERIR_AGENDA = "TRANSFERIR_AGENDA";
	private static final String CONSULTA_AGENDA_SEM_RESPONSAVEL = "CONSULTA_AGENDA_SEM_RESPONSAVEL";
	private static final String PAGINA_FORMULARIO = "/pages/agenda/geral/agenda-geral-form.xhtml?faces-redirect=true";
	private static final String CUMPRIDO = "Cumprido";

	@Inject
	private PessoaFisicaSessionBean pessoaFisicaSessionBean;
	@Inject
	private PessoaSessionBean pessoaSessionBean;
	@Inject
	private EventoSessionBean eventoSessionBean;
	@Inject
	private StatusAgendaSessionBean statusAgendaSessionBean;
	@Inject
	private EmailSessionBean emailSessionBean;
	@Inject
	private EmailCaixaSaidaSessionBean emailCaixaSaidaSessionBean;

	private Evento eventoSelecionado = new Evento();
	private ScheduleEvent event = new DefaultScheduleEvent();
	private Map<PessoaFisica, List<Evento>> pessoaEventosMap = Maps.newHashMap();
	private List<PessoaAgendaDto> menuPessoas = Lists.newArrayList();
	private String pessoaFisicaSelecionada;
	private Evento eventoAnterior;

	@PostConstruct
	public void initializeAgendas() {
		String flash = (String) getFlashScope().get(PESSOA_SELECT_FLASH);
		if (!Strings.isNullOrEmpty(flash)) {
			pessoaFisicaSelecionada = flash;
		} else {
			pessoaFisicaSelecionada = TODOS;
		}
		carregaPessoaEventosDaAgenda();
		carregaLazyEvent();
	}

	private void carregaPessoaEventosDaAgenda() {
		List<PessoaFisica> pessoas = getAdvogadosColaboradores();
		for (PessoaFisica pf : pessoas) {
			List<Evento> eventos = getEventosDaPessoa(pf);
			if (!eventos.isEmpty()) {
				pessoaEventosMap.put(pf, eventos);
			}
		}
		carregaMenuAgenda();
	}

	private void carregaLazyEvent() {
		if (!Strings.isNullOrEmpty(pessoaFisicaSelecionada)) {
			carregaLazyEventModel();
		} else {
			setLazyEventModel(new LazyScheduleModel());
		}
	}

	@Override
	protected List<Evento> listaDeEventos() {
		return carregaEventos(getDataInicioAgenda(), getDataFimAgenda());
	}


	private List<Evento> carregaEventos(Date start, Date end) {
		if (TODOS.equals(pessoaFisicaSelecionada)) {
			return getTodosEventosDaEmpresa(start, end);
		}
		if(INDEFINIDO.equals(pessoaFisicaSelecionada)){
			return getEventosPessoasIndefinidas(start, end);
		}

		Pessoa pessoa = pessoaSessionBean.findByNome(pessoaFisicaSelecionada, getStateManager().getEmpresaSelecionada().getId());
		eventoSessionBean.clearSession();
		return eventoSessionBean.findUserEvents(pessoa, start, end, getStateManager().getEmpresaSelecionada().getId());
	}

	public void onEventSelect(SelectEvent selectEvent) {
		event = (ScheduleEvent) selectEvent.getObject();
		setEventoSelecionado(eventoSessionBean.findByChaveId((String) event.getData()));
		RequestContext.getCurrentInstance().execute("PF('eventDialog').show();");
	}

	public void selectPessoa(String nomePessoaFisica) {
		pessoaFisicaSelecionada = nomePessoaFisica;
		getFlashScope().put(PESSOA_SELECT_FLASH, pessoaFisicaSelecionada);
	}

	public List<StatusAgenda> getStatus(){
		return statusAgendaSessionBean.findAllStatusAtivos(getStateManager().getEmpresaSelecionada().getId());
	}

	private void carregaMenuAgenda() {
		for (Entry<PessoaFisica, List<Evento>> entry : pessoaEventosMap.entrySet()) {
			Pessoa pessoa = entry.getKey().getPessoa();
			PessoaAgendaDto pessoaEstilo = new PessoaAgendaDto(pessoa.getDescricao(), pessoa.getImagem(), pessoa.getNomeIniciais());
			menuPessoas.add(pessoaEstilo);
		}

		if (!menuPessoas.isEmpty()) {
			Collections.sort(menuPessoas, (o1, o2) -> o1.toString().compareTo(o2.toString()));
			menuPessoas.add(0, new PessoaAgendaDto(TODOS, null, null));

			if (isHasAccessAgendaSemResponsavel()) {
				boolean existeEventoComResponsavelIndefinido = eventoSessionBean.isExisteEventoComPessoaIndefinida(getStateManager().getEmpresaSelecionada().getId());
				if (existeEventoComResponsavelIndefinido) {
					menuPessoas.add(1, new PessoaAgendaDto(INDEFINIDO, null, null));
				}
			}

		}
		setPessoaMenuList(menuPessoas);
	}

	public void addEvent(ActionEvent actionEvent) {
		try {
			atualizarEvento();
			RequestContext.getCurrentInstance().execute("PF('myschedule').update(); PF('eventDialog').hide();");
		} catch (ValidationException e) {
			LOGGER.error(e, e.getCause());
		}
	}

	public void transferenciaChanged(ValueChangeEvent event) {
		boolean transferir = (boolean) event.getNewValue();
		if (!transferir && eventoSelecionado!= null) {
			Pessoa pessoa = pessoaSessionBean.retrieve(getUser().getId());
			this.eventoSelecionado.setPessoa(pessoa);
		}
	}

	public void excluir() throws ValidationException {
		getLazyEventModel().updateEvent(event);
		if (getEventoSelecionado() != null) {
			eventoSessionBean.clearSession();
			eventoSessionBean.delete(getEventoSelecionado().getId());
		}
		enviarEmailRemocao(getEventoSelecionado());
	}

	public void statusChanged(ValueChangeEvent event){
		StatusAgenda statusAgenda = (StatusAgenda) event.getNewValue();
		this.eventoSelecionado.setStatusAgenda(statusAgenda);
	}

	private void enviarEmailRemocao(Evento evento){
		Email email = emailSessionBean.findBySigla(AGENDA_EXCLUIR_EVENTO, getStateManager().getEmpresaSelecionada().getId());
		Map<String, String> parametersValues = Maps.newHashMap();

		if (email == null) {
			exibirMensagem(FacesMessage.SEVERITY_INFO, "Email para Exclusão de evento não cadastrado...");
			return;
		}

		for (EmailVinculoParametro parametro : email.getParametroEmails()) {
			String valor = AgendaEmailBusiness.execute(parametro.getParametroEmail(), evento, new Evento(), getUser());
			parametersValues.put(parametro.getParametroEmail().getSigla(), valor);
		}

		String textoFormatado = EmailTemplateBusiness.criarEmailTemplate(email.getAssunto(), email.getDescricao(), parametersValues);
		enviarEmail(email, textoFormatado);
	}

	@Override
	protected void updateEvento() {
		try {
			Pessoa pessoa = this.eventoSelecionado.getPessoa();

			if(pessoa != null) {
				this.eventoSelecionado.setNomeIniciais(pessoa.getNomeIniciais());
			}
			if(this.eventoSelecionado.getAndamento() != null && this.eventoSelecionado.getPrazoAndamento() == null){
				this.eventoSelecionado.getAndamento().setStatusAgenda(this.eventoSelecionado.getStatusAgenda());
			} else if(this.eventoSelecionado.getPrazoAndamento() != null) {
				this.eventoSelecionado.getPrazoAndamento().setStatusAgenda(this.eventoSelecionado.getStatusAgenda());
			}

			adicionaControladoria(Boolean.TRUE);
			HistoricoEvento historicoEvento = new HistoricoEvento(this.eventoSelecionado, getUser().getName());
			historicoEvento.setTipoOperacao(TipoOperacaoIndicador.ALT);
			this.eventoSelecionado.addHistorico(historicoEvento);
			carregarEventoAnterior();
			eventoSessionBean.update(this.eventoSelecionado);
			enviarEmailAlteracao();
		} catch (ValidationException e) {
			LOGGER.error(e, e.getCause());
		}
	}

	private void adicionaControladoria(boolean edicao) {
		boolean possuiConfControladoria = getUser().getEmpresa() == null ? Boolean.FALSE : getUser().getEmpresa().isConfiguracaoControladoria();
		ControladoriaContext context = new ControladoriaContext();
		ControladoriaState aprovacaoState = new AprovaControladoria();
		context.setState(aprovacaoState);

		this.eventoSelecionado.setControladoriaStatus(context.controladoriaAction(
				edicao, this.eventoSelecionado.getStatusAgenda(),
				possuiConfControladoria,
				ControladoriaIndicador.fromValue(this.eventoSelecionado.getControladoriaStatus())).getStatus());
	}

	private void carregarEventoAnterior() throws ValidationException {
		Evento evento = new Evento();
		eventoSessionBean.clearSession();
		if (this.eventoSelecionado != null && this.eventoSelecionado.getId() != null) {
			evento = eventoSessionBean.retrieve(this.eventoSelecionado.getId());
		}
		this.eventoAnterior = evento;
		eventoSessionBean.clearSession();
	}

	private void atualizarEvento() throws ValidationException {
		super.atualizarEvento(getEventoSelecionado(), this.event);
		setEventoSelecionado(null);
	}

web-juridico-webapp/src/main/webapp/pages/agenda/geral/agenda-geral-form.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
		"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	  xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	  xmlns:p="http://primefaces.org/ui"
	  xmlns:h="http://xmlns.jcp.org/jsf/html"
	  xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	  xmlns:f="http://java.sun.com/jsf/core"
	  xmlns:stpro="http://java.sun.com/jsf/composite/stprocomponents">

<ui:composition template="../../../plain-template.xhtml">
	<!-- TITULO DA PAGINA -->
	<ui:define name="page-title">
		<div class="page-title">${bundleMsgs.label_agenda_geral}</div>
	</ui:define>

	<ui:define name="left_menu">
		<!-- ACTIVE MENU -->
		<ui:param name="active_home" value="" />
		<ui:param name="active_processos" value="" />
		<ui:param name="active_agenda" value="active" />
		<ui:param name="active_cadastros" value="" />
		<ui:param name="active_contratos" value="" />
		<ui:param name="active_controladoria" value="" />
		<ui:param name="active_clientes" value="" />
		<ui:param name="active_financeiro" value="" />
		<ui:param name="active_relatorios" value="" />
		<ui:param name="active_atendimento" value="" />
		<ui:param name="active_acessos" value="" />

		<!-- MENU LATERAL -->
		<ui:include src="../../../left-menu-template.xhtml" />
	</ui:define>

	<!-- BREADCRUMB -->
	<ui:define name="breadcrumb">
		<li><h:link outcome="/pages/index.xhtml">
			<i class="fa fa-home"></i>
			Home
		</h:link></li>
		<li><h:link outcome="/pages/agenda/list-agenda.xhtml">
			${bundleMsgs.agenda}
		</h:link></li>
		<li class="active">${bundleMsgs.label_agenda_geral}</li>
	</ui:define>
	<!-- FIM DO BREADCRUMB -->

	<ui:define name="content">
		<h:form id="minhaAgendaForm" prependId="false">
			<!-- Mensagens ******************************** -->
			<div class="row">
				<div class="col-xs-12 form-group">
					<ui:include src="../../../_mensagens.xhtml" />
				</div>
			</div>
			<!-- Mensagens ................................ -->

			<div class="row">
				<div class="col-md-4">
					<div class="box box-solid col-md-12 no-padding">
						<div class="box-header with-border">
							<h3 class="box-title">#{bundleMsgs.pessoas}</h3>
							<div class="box-tools">
								<button class="btn btn-box-tool" data-widget="collapse">
									<i class="fa fa-minus"></i>
								</button>
							</div>
						</div>
						<div class="box-body">
							<ul class="nav nav-pills nav-stacked">
								<ui:repeat value="#{agendaGeralController.menuPessoas}" var="row">
									<li class="#{row.nome eq agendaGeralController.pessoaFisicaSelecionada ? 'active' : ''}">
										<h:commandLink action="#{agendaGeralController.selectPessoa(row.nome)}" immediate="true">
											<h:graphicImage alt="Imagem" styleClass="user-image" height="32" width="32"
															value="/image?idImagem=#{row.imagem.id}&amp;nome=#{row.imagem.nomeArquivo}"
															rendered="#{row.nome ne 'Todos' and row.nome ne 'Indefinido'}"/>

											<h:graphicImage alt="Imagem" styleClass="user-image" height="32" width="32"
															value="/resources/images/avatar/users_business.png"
															rendered="#{row.nome eq 'Todos'}"/>

											<h:graphicImage alt="Imagem" styleClass="user-image" height="32" width="32"
															value="/resources/images/avatar/questions.png"
															rendered="#{row.nome eq 'Indefinido'}"/>

											<span> <h:outputText value="#{row.nome}" style="padding-left: 5px; padding-right: 5px;"/></span>

											<h:panelGroup rendered="#{row.nomeIniciais ne null}" >
												<span class="label label-default">
													<h:outputText value="#{row.nomeIniciais}"/>
												</span>
											</h:panelGroup>
										</h:commandLink>
									</li>
								</ui:repeat>
							</ul>
						</div>
						<div class="box-footer"></div>
					</div>
				</div>

				<div class="col-md-8">
					<div class="box box">
						<div class="box-body">
							<!-- schedule-->
							<p:schedule id="schedule"
										value="#{agendaGeralController.lazyEventModel}"
										widgetVar="myschedule"
										timeZone="#{agendaGeralController.timeZone}" locale="pt"
										slotMinutes="30" axisFormat="HH:mm" timeFormat="HH:mm"
										view="agendaWeek" styleClass="custom" firstHour="6"
										minTime="06:00" maxTime="21:30" tooltip="true" >
								<p:ajax event="eventSelect"
										listener="#{agendaGeralController.onEventSelect}"
										update="eventDetails"  />
							</p:schedule>
						</div>
					</div>
				</div>
			</div>

			<p:dialog widgetVar="eventDialog"
					  header="${bundleMsgs.label_evento_titulo_header}" modal="true"
					  width="600" resizable="false">

				<div class="ui-fluid">
					<h:panelGroup id="eventDetails">
						<p:panelGrid columns="2"
									 columnClasses="ui-grid-col-2, ui-grid-col-10" layout="grid"
									 styleClass="ui-panelgrid-blank">

							<p:outputLabel value="${bundleMsgs.label_evento_titulo}:" />
							<h:outputText value="#{agendaGeralController.eventoSelecionado.descricao}" />

							<p:outputLabel value="${bundleMsgs.label_processo}:" />
							<h:outputText value="#{agendaGeralController.eventoSelecionado.processo.toString()}" rendered="#{not empty agendaGeralController.eventoSelecionado.processo.toString()}" />
							<h:outputText value="Não vinculado" rendered="#{empty agendaGeralController.eventoSelecionado.processo.toString()}" />

							<p:outputLabel value="${bundleMsgs.label_partes}:" rendered="#{agendaGeralController.eventoSelecionado.processo ne null}" />
							<p:outputPanel id="partes" class="ui-fluid"  rendered="#{agendaGeralController.eventoSelecionado.processo ne null}">
								<p:dataTable id="table" var="p" value="#{agendaGeralController.eventoSelecionado.processo.partes}" row="rowIndex">
									<p:column headerText="#{bundleMsgs.label_nome}" style="width: 70%;">
										<h:outputText value="#{p.pessoa.descricao}"  />
									</p:column>

									<p:column headerText="#{bundleMsgs.label_posicao}" style="width: 30%; text-align: center;">
										<h:outputText value="#{p.posicao.descricao}"  />
									</p:column>
								</p:dataTable>
							</p:outputPanel>

							<h:outputLabel value="${bundleMsgs.label_evento_local}" />
							<h:outputText value="#{agendaGeralController.eventoSelecionado.localizacao}" rendered="#{not empty agendaGeralController.eventoSelecionado.localizacao}" />
							<h:outputText value="Indefinido" rendered="#{empty agendaGeralController.eventoSelecionado.localizacao}"/>

							<p:outputLabel value="${bundleMsgs.label_evento_de}:" />
							<p:inputMask mask="99/99/9999 99:99" pt:placeholder="dd/MM/aaaa HH:mm"
										 disabled="#{agendaGeralController.eventoSelecionado.controladoriaStatus eq 'P'}"
										 value="#{agendaGeralController.eventoSelecionado.dataInicio}">
								<f:convertDateTime pattern="dd/MM/yyyy HH:mm" />
                                <p:ajax event="change" process="@this" update="buttonSave" />
							</p:inputMask>

							<p:outputLabel value="${bundleMsgs.label_evento_ate}:" />
							<p:inputMask mask="99/99/9999 99:99" pt:placeholder="dd/MM/aaaa HH:mm"
										 disabled="#{agendaGeralController.eventoSelecionado.controladoriaStatus eq 'P'}"
										 value="#{agendaGeralController.eventoSelecionado.dataFim}">
								<f:convertDateTime pattern="dd/MM/yyyy HH:mm" />
                                <p:ajax event="change" process="@this" update="buttonSave" />
							</p:inputMask>

							<h:outputLabel value="${bundleMsgs.label_status}" />
							<h:selectOneMenu class="form-control"
											 disabled="#{agendaGeralController.eventoSelecionado.controladoriaStatus eq 'P'}"
											 value="#{agendaGeralController.eventoSelecionado.statusAgenda}"
											 converter="entityConverter" valueChangeListener="#{agendaGeralController.statusChanged}">
								<f:selectItems value="#{agendaGeralController.status}" var="status"
											   itemLabel="#{status.descricao}" itemValue="#{status}" />

								<p:ajax event="change" process="@this" update="eventDetails" />
							</h:selectOneMenu>

							<h:outputLabel value="${bundleMsgs.label_houve_acordo}" for="edtAndamentoHouveAcordo"
										   rendered="#{agendaGeralController.renderizaHouveAcordoAndamento}"/>

							<p:selectOneRadio id="edtAndamentoHouveAcordo" value="#{agendaGeralController.eventoSelecionado.andamento.houveAcordo}"
											  class="form-control radio-group"
											  rendered="#{agendaGeralController.renderizaHouveAcordoAndamento}">
								<f:selectItem itemValue="#{true}"
											  itemLabel="${bundleMsgs.label_sim}" />
								<f:selectItem itemValue="#{false}"
											  itemLabel="${bundleMsgs.label_nao}" />
							</p:selectOneRadio>

							<div class="form-control" style="border: none;" />
							<p:selectBooleanCheckbox
									rendered="#{agendaGeralController.hasAccessTransferir and agendaGeralController.eventoSelecionado.controladoriaStatus ne 'P'}"
									value="#{agendaGeralController.eventoSelecionado.transferir}"
									itemLabel="${bundleMsgs.label_evento_transferir}"
									valueChangeListener="#{agendaGeralController.transferenciaChanged}">
								<p:ajax event="change" process="@this" update="eventDetails" />
							</p:selectBooleanCheckbox>

							<p:outputLabel value="${bundleMsgs.label_para}:"
										   rendered="#{agendaGeralController.eventoSelecionado.transferir}" />
							<h:selectOneMenu class="form-control"
											 rendered="#{agendaGeralController.eventoSelecionado.transferir}"
											 value="#{agendaGeralController.eventoSelecionado.pessoa}"
											 converter="entityConverter">
								<f:selectItem itemLabel="Selecione..." itemValue="#{null}" />
								<f:selectItems var="adv" itemLabel="#{adv.pessoa.descricao}"
											   itemValue="#{adv.pessoa}"
											   value="#{agendaGeralController.advogadosColaboradoresEscritorioList}" />
							</h:selectOneMenu>
						</p:panelGrid>

						<h:panelGroup rendered="#{agendaGeralController.eventoSelecionado.controladoriaStatus eq 'P'}">
							<div class="col-xs-12 form-group" align="right">
								<span class="label label-sm label-warning">#{bundleMsgs['fields.form.controladoria.message']}</span>
							</div>
						</h:panelGroup>

						<h:panelGroup rendered="#{agendaGeralController.eventoSelecionado.controladoriaStatus ne 'P'}">
							<p:spacer height="30" />
							<div class="col-xs-12 form-group" align="right">
								<h:commandLink value="#{bundleMsgs.bt_excluir}"
											   rendered="#{agendaGeralController.eventoSelecionado.controladoriaStatus ne 'P'}"
											   onclick="PF('myschedule').update(); PF('eventDialog').hide();"
											   class="btn btn-danger" style="color: #fff !important;">
									<f:ajax onevent="openModal('#myModal')" />
								</h:commandLink>
								<span />

								<h:commandButton id="buttonSave" value="#{bundleMsgs.bt_salvar}" class="btn btn-success"
												 rendered="#{agendaGeralController.eventoSelecionado.controladoriaStatus ne 'P'}"
												 actionListener="#{agendaGeralController.addEvent}"
								                disabled="#{agendaGeralController.eventoSelecionado.dataInicio eq null or
								                            agendaGeralController.eventoSelecionado.dataFim eq null}"/>
							</div>
						</h:panelGroup>

					</h:panelGroup>
				</div>


			</p:dialog>

			<!-- COMPONENTE POPUP -->
			<stpro:exclusion-popup controller="#{agendaGeralController}" />
		</h:form>

	</ui:define>
</ui:composition>
</html>