web-juridico-webapp/src/main/java/br/com/juridico/controller/CrudController.java
package br.com.juridico.controller;

import br.com.juridico.dao.IEntity;
import br.com.juridico.enums.CrudStatus;
import br.com.juridico.exception.CrudException;
import br.com.juridico.exception.ValidationException;
import org.apache.log4j.Logger;
import org.primefaces.model.LazyDataModel;

import javax.faces.application.FacesMessage;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Jefferson Ferreira
 *
 * @param <T>
 */
public abstract class CrudController<T extends IEntity> extends AbstractController {

	/**
	 *
	 */
	private static final long serialVersionUID = -5595574461745839844L;

	private static final Logger LOGGER = Logger.getLogger(CrudController.class);

	protected static final String LIST_FLASH = "LIST_FLASH";

	private boolean editavel;
	protected CrudStatus crudStatus;
	private String descricaoFiltro;
	private String chaveAcesso;
	private T objetoSelecionado;
	private List<T> lista;
	private LazyDataModel<T> lazyDataModel;

	protected boolean permiteVisualizacaoEmail;
	protected boolean permiteInclusaoEmail;
	protected boolean permiteExclusaoEmail;
	protected boolean permiteVisualizacaoContato;
	protected boolean permiteInclusaoContato;
	protected boolean permiteExclusaoContato;
	protected boolean permiteVisualizacaoEndereco;
	protected boolean permiteInclusaoEndereco;
	protected boolean permiteExclusaoEndereco;
	protected boolean permiteVisualizacaoResponsavel;
	protected boolean permiteInclusaoResponsavel;
	protected boolean permiteExclusaoResponsavel;
	protected boolean permiteVisualizacaoCentroCusto;
	protected boolean permiteInclusaoCentroCusto;
	protected boolean permiteExclusaoCentroCusto;


	/**
	 *
	 */
	public CrudController() {
		try {
			selecionar(null);
		} catch (CrudException e) {
			LOGGER.error(e.getLocalizedMessage(), e);
		}
	}

	/**
	 *
	 * @param objeto
	 */
	public void editar(T objeto) {
		try {
			if (selecionar(objeto)) {
				editar();
			}
		} catch (CrudException e) {
			LOGGER.info(e.getCause(), e);
			exibirMensagem(e.getMensagemListDetalhe(), e.getMessage());
		}
	}

	/**
	 *
	 */
	public void limparObjetoSelecionado() {
		try {
			this.objetoSelecionado = instanciarObjetoNovo();
			aposLimparObjetoSelecionado();
		} catch (CrudException e) {
			LOGGER.error(e);
		}
	}

	/**
	 *
	 */
	public void editar() {
		try {
			validarEdicao();
			antesDeEditar(objetoSelecionado);
			crudStatus = CrudStatus.UPDATE;
			aposEditar();
		} catch (CrudException e) {
			LOGGER.error(e);
			exibirMensagem(e.getMensagemListDetalhe(), getMessage("msg_erro_editar"));
		}
	}

	private void validarEdicao() throws CrudException {
		if (objetoSelecionado == null) {
			throw new CrudException(getMessage("msg_selecione_registro_para_editar"));
		}
	}

	/**
	 *
	 */
	public void salvar() {
		try {
			antesDeSalvar();
			setEmpresaDeUsuarioLogado(objetoSelecionado);
			validar();
			salvarAposValidacao();
			exibirMensagem(FacesMessage.SEVERITY_INFO, getMessage("msg_sucesso_salvar"));
		} catch (CrudException e) {
			LOGGER.info(e.getCause(), e);
			exibirMensagem(e.getMensagemListDetalhe(), getMessage("msg_erro_salvar"));
		} catch (ValidationException e) {
			for (String message : e.getMessages()) {
				exibirMensagem(FacesMessage.SEVERITY_ERROR, message);
			}
		} finally {
			aposValidacao();
		}
	}

	/**
	 *
	 * @throws CrudException
	 * @throws ValidationException
	 */
	public void salvarAposValidacao() throws CrudException, ValidationException {
		create(objetoSelecionado);
		addicionarObjetoNaLista(objetoSelecionado);
		crudStatus = null;
		selecionarObjetoAposSalvar();
		aposSalvar();
	}

	/**
	 *
	 * @param objeto
	 */
	public void excluir(T objeto) {
		try {
			if (selecionar(objeto)) {
				excluir();
			}
		} catch (CrudException e) {
			LOGGER.info(e.getCause(), e);
			exibirMensagem(e.getMensagemListDetalhe(), e.getMessage());
		} catch (ValidationException e) {
			LOGGER.error(e.getLocalizedMessage(), e);
		}
	}

	/**
	 *
	 * @throws ValidationException
	 */
	public void excluir() throws ValidationException {
		try {
			antesDeExcluir();
			salvarAposValidacao();
			aposExcluir();
			exibirMensagem(FacesMessage.SEVERITY_INFO, getMessage("msg_sucesso_excluir"));
		} catch (CrudException e) {
			LOGGER.info(e.getCause(), e);
			exibirMensagem(e.getMensagemListDetalhe(), getMessage("msg_erro_excluir"));
		}
	}

	/**
	 *
	 */
	public void cancelar() {
		if (objetoSelecionado.getId() != null)
			objetoSelecionado = inicializaObjetosLazy(objetoSelecionado);

		limparObjetoSelecionado();
		crudStatus = null;
		try {
			selecionar(null);
			buscarPorLazy();
			aposCancelar();
		} catch (CrudException e) {
			LOGGER.info(e.getCause(), e);
			exibirMensagem(e.getMensagemListDetalhe(), getMessage("msg_erro_cancelar"));
		}
	}

	/**
	 *
	 * @param objeto
	 * @return
	 * @throws CrudException
	 */
	public boolean selecionar(T objeto) throws CrudException {
		if (CrudStatus.CREATE.equals(crudStatus) || validarEdicao(objeto)) {
			antesDeSelecionar(objeto);

			if (objeto == null) {
				objeto = instanciarObjetoNovo();
				if (objeto instanceof IEntity == false) {
					LOGGER.error(objeto.getClass() + " deve extender IEntity");
				}
			}

			if (objeto.getId() != null) {
				objeto = inicializaObjetosLazy(objeto);
			}
			objetoSelecionado = objeto;
			aposSelecionar();
			return true;
		}

		return false;
	}

	/**
	 *
	 * @param objeto
	 */
	public void visualizar(T objeto) {
		try {
			selecionar(objeto);
			crudStatus = CrudStatus.READ;
		} catch (CrudException e) {
			LOGGER.info(e.getCause(), e);
			exibirMensagem(e.getMensagemListDetalhe(), e.getMessage());
		}

	}

	/**
	 *
	 * @param novoRegistro
	 */
	public void novo(T novoRegistro) {
		insereNovoRegistro(novoRegistro);
	}

	/**
	 *
	 */
	public void novo() {
		T novoRegistro = instanciarObjetoNovo();
		insereNovoRegistro(novoRegistro);
	}

	/**
	 *
	 * @param novoRegistro
	 */
	public void insereNovoRegistro(T novoRegistro) {
		try {
			crudStatus = CrudStatus.CREATE;
			selecionar(novoRegistro);
			antesInserir();
			depoisInserir();
		} catch (CrudException e) {
			LOGGER.info(e.getCause(), e);
			exibirMensagem(e.getMensagemListDetalhe(), getMessage("msg_erro_inserir"));
		}
	}

	/**
	 *
	 * @return
	 */
	public boolean isEditavel() {
		this.editavel = Boolean.FALSE;

		if (CrudStatus.CREATE.equals(crudStatus)) {
			this.editavel = Boolean.TRUE;
		}

		if (CrudStatus.UPDATE.equals(crudStatus)) {
			this.editavel = Boolean.TRUE;
		}

		if (CrudStatus.DELETE.equals(crudStatus)) {
			this.editavel = Boolean.TRUE;
		}

		return this.editavel;
	}

	/**
	 *
	 * @param objeto
	 * @return
	 */
	public boolean validarEdicao(T objeto) {
		if (!permiteEditar(objeto)) {
			exibirMensagem(FacesMessage.SEVERITY_WARN, getMessage("msg_cancele_salve_registro_em_edicao"));
			return false;
		} else {
			return true;
		}
	}

	/**
	 *
	 * @param objeto
	 * @return
	 */
	public boolean permiteEditar(T objeto) {
		return CrudStatus.UPDATE.equals(crudStatus) || !CrudStatus.CREATE.equals(crudStatus);
	}

	/**
	 *
	 * @throws CrudException
	 */
	public void selecionarObjetoAposSalvar() throws CrudException {
		selecionar(null);
	}

	/**
	 *
	 * @param objeto
	 */
	public void addicionarObjetoNaLista(T objeto) {
		if (lista == null) {
			lista = new ArrayList<>();
		}

		if (!lista.contains(objeto)) {
			lista.add(objeto);
		}
	}

	/**
	 *
	 * @param novoObjeto
	 */
	public void clearObjetoSelecionado(T novoObjeto) {
		this.objetoSelecionado = novoObjeto;
	}

	public T getObjetoSelecionado() {
		return objetoSelecionado;
	}

	public void setObjetoSelecionado(T objetoSelecionado) {
		this.objetoSelecionado = objetoSelecionado;
	}

	/**
	 *
	 */
	public void buscarPorLazy() {
		carregaLazyDataModel();
	}

	public List<T> getLista() {
		if (lista == null) {
			return new ArrayList<>();
		}
		return lista;
	}

	public boolean isHasAccess(){
		addChaveAcesso();
		return possuiAcesso(this.chaveAcesso);
	}

	public void setLista(List<T> lista) {
		this.lista = lista;
	}

	public void setEditavel(boolean editavel) {
		this.editavel = editavel;
	}

	protected void antesDeSelecionar(T objeto) throws CrudException {
	}

	protected void aposSelecionar() throws CrudException {
	}

	protected void depoisInserir() throws CrudException {
	}

	protected void antesInserir() throws CrudException {
	}

	protected void antesDeSalvar() throws CrudException {
	}

	protected void aposSalvar() throws CrudException {
	}

	protected void aposExcluir() throws CrudException {
	}

	protected void antesDeExcluir() throws CrudException {
	}

	protected void antesDeBuscar() throws CrudException {
	}

	protected void aposBuscar() throws CrudException {
	}

	protected void antesDeEditar(T objeto) throws CrudException {
	}

	protected void aposLimparObjetoSelecionado() throws CrudException {
	}

	protected void validar() throws ValidationException {
	}

	protected void aposValidacao() {
	}

	protected void aposEditar() throws CrudException {
		buscarPorLazy();
	}

	protected void aposCancelar() throws CrudException {
	}

	protected abstract void create(T objetoSelecionado) throws ValidationException, CrudException;

	protected abstract void carregaLazyDataModel();

	protected abstract T inicializaObjetosLazy(T objetoSelecionado);

	protected abstract T instanciarObjetoNovo();

	protected abstract void setEmpresaDeUsuarioLogado(T objetoSelecionado);

	protected abstract void addChaveAcesso();

	protected abstract boolean isPodeAlterar();

	protected abstract boolean isPodeExcluir();

	protected abstract boolean isPodeIncluir();

	public String getDescricaoFiltro() {
		return descricaoFiltro;
	}

	public void setDescricaoFiltro(String descricaoFiltro) {
		this.descricaoFiltro = descricaoFiltro;
	}

	public LazyDataModel<T> getLazyDataModel() {
		return lazyDataModel;
	}

	public void setLazyDataModel(LazyDataModel<T> lazyDataModel) {
		this.lazyDataModel = lazyDataModel;
	}


	public void setChaveAcesso(String chaveAcesso) {
		this.chaveAcesso = chaveAcesso;
	}

web-juridico-webapp/src/main/webapp/pages/processos/tabs/tab-confirmacao.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">

    <div class="row">
        <div class="col-md-12 col-xs-12 form-group">
            <div class="box-header with-border">
                <h3 class="box-title">${bundleMsgs.label_confirmacao}</h3>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4 col-xs-12 form-group">
            <h4>#{bundleMsgs.label_status_processo}</h4>
            <h:selectOneMenu
                    value="#{cadastroProcessoController.processo.status}"
                    styleClass="form-control select2">
                <f:selectItems var="status"
                               value="#{cadastroProcessoController.statusProcessoItems}"
                               itemLabel="#{status.descricao}" itemValue="#{status.value}" />
            </h:selectOneMenu>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12 col-xs-12 form-group">
            <p:selectBooleanCheckbox styleClass="left-checkbox"
                                     value="#{cadastroProcessoController.processo.privado}" itemLabel="${bundleMsgs.label_privado}">
                <f:ajax event="change" execute="@this" />
            </p:selectBooleanCheckbox>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 form-group" align="right">
            <!--Cancelar-->
            <h:commandButton id="btnCancelar" value="#{bundleMsgs.bt_cancelar}"
                             class="btn btn-default"
                             action="#{cadastroProcessoController.cancelarProcesso()}"
                             pt:data-loader="off" immediate="true">
            </h:commandButton>

            <!--Inserir-->
            <h:commandButton id="btnInserir" value="#{bundleMsgs.bt_novo}"
                             class="btn btn-success" action="#{cadastroProcessoController.goToCadastroProcessos()}">
            </h:commandButton>

            <!--Salvar-->
            <h:commandButton id="btnSalvar" value="#{bundleMsgs.bt_salvar}"
                             class="btn btn-primary" pt:data-loader="on"
                             pt:data-loader-message="Salvando, Aguarde..."
                             onclick="setConfirmUnload(false)"
                             action="#{cadastroProcessoController.salvar()}">
            </h:commandButton>
        </div>
    </div>
</ui:composition>

web-juridico-webapp/src/main/webapp/pages/processos/tabs/tab-resumo-acao.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">

	<div class="row">
		<div class="col-md-12 col-xs-12 form-group">
            <div class="box-header with-border">
                <h3 class="box-title">${bundleMsgs.label_resumo_acao}</h3>
            </div>
		</div>
	</div>

    <div class="row">
        <div class="col-md-12 col-xs-12">
            <p:editor id="editor" widgetVar="editorWidget" value="#{cadastroProcessoController.processo.observacao}" style="width: 100%"
                      disabled="#{cadastroProcessoController.processo.processoFinalizado}"/>
        </div>
    </div>
</ui:composition>

web-juridico-webapp/src/main/webapp/pages/processos/tabs/tab-valores-acao.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">

    <div class="row">
        <div class="col-md-12 col-xs-12 form-group">
            <div class="box-header with-border">
                <h3 class="box-title">${bundleMsgs.label_valores_acao}</h3>
            </div>
        </div>
    </div>

    <h:panelGroup id="valoresFormGroup">
        <h:panelGroup rendered="#{cadastroProcessoController.processo.provavelNecessidadeImpugnacao}">
            <div class="row">
                <div class="col-md-12 col-xs-12 form-group">
                    <div class="static-alert-danger">
                        <strong>Aviso: </strong>
                        <h:outputText value="${bundleMsgs.info_necessidade_impugnacao}" />
                    </div>
                </div>
            </div>
        </h:panelGroup>

        <div class="row">
            <div class="col-md-12 col-xs-12 form-group">
                <p:panel id="panelPedidos" header="${bundleMsgs.label_pedido}s" style="margin-bottom:20px">
                    <p:panelGrid columns="4" columnClasses="ui-grid-col-3,ui-grid-col-3,ui-grid-col-3,ui-grid-col-3" layout="grid" styleClass="ui-panelgrid-blank">

                        <h:panelGroup class="form-group">
                            <h4>#{bundleMsgs.label_pedido} *</h4>
                        </h:panelGroup>
                        <h:panelGroup class="form-group">
                            <h4>#{bundleMsgs.label_causa_pedido} *</h4>
                        </h:panelGroup>
                        <h:panelGroup class="form-group">
                            <h4>#{bundleMsgs.label_valor_pedido} *</h4>
                        </h:panelGroup>
                        <h:panelGroup class="form-group">
                            <h4>#{bundleMsgs.label_valor_provavel} *</h4>
                        </h:panelGroup>

                        <h:panelGroup id="pedidoGroup" class="input-group">
                            <h:selectOneMenu value="#{cadastroProcessoController.pedidoSelecionado.pedido}"
                                             style="height: 34px;" styleClass="form-control"
                                             disabled="#{cadastroProcessoController.processo.processoFinalizado}"
                                             converter="entityConverter" pt:data-loader="off">
                                <f:selectItem itemLabel="" itemValue="#{null}" />
                                <f:selectItems var="p" value="#{processoListasController.pedidos}"
                                               itemLabel="#{p.descricao}" />
                                <f:ajax event="change" execute="pedidoGroup" />
                            </h:selectOneMenu>
                            <span class="input-group-btn">
                                <h:commandLink class="btn btn-input" title="${bundleMsgs.bt_adicionar}"
                                               disabled="#{cadastroProcessoController.processo.processoFinalizado}"
                                               rendered="#{pedidoController.hasAccess}">
                                    <i class="fa fa-plus"></i>
                                    <p:ajax process="@this" listener="#{cadastroProcessoController.abrirPedidoListener()}"  />
                                </h:commandLink>
                            </span>
                        </h:panelGroup>

                        <h:panelGroup id="causaPedidoGroup" class="input-group">
                            <h:selectOneMenu value="#{cadastroProcessoController.pedidoSelecionado.causaPedido}"
                                             style="height: 34px;" styleClass="form-control select2"
                                             disabled="#{cadastroProcessoController.processo.processoFinalizado}"
                                             converter="entityConverter" pt:data-loader="off">
                                <f:selectItem itemLabel="" itemValue="#{null}" />
                                <f:selectItems var="c"
                                               value="#{processoListasController.causasPedido}"
                                               itemLabel="#{c.descricao}" />
                                <f:ajax event="change" execute="causaPedidoGroup" />
                            </h:selectOneMenu>
                            <span class="input-group-btn">
                                <h:commandLink class="btn btn-input"
                                               rendered="#{causaPedidoController.hasAccess}"
                                               title="#{cadastroProcessoController.processo.processoFinalizado ? bundleMsgs.bt_processo_finalizado : bundleMsgs.bt_adicionar}"
                                               disabled="#{cadastroProcessoController.processo.processoFinalizado}">
                                    <i class="fa fa-plus"></i>
                                    <p:ajax process="@this" listener="#{cadastroProcessoController.abrirCausaPedidoListener()}"  />
                                </h:commandLink>
                            </span>
                        </h:panelGroup>

                        <p:inputNumber id="valorPedido" value="#{cadastroProcessoController.pedidoSelecionado.valorPedido}"
                                       disabled="#{cadastroProcessoController.processo.processoFinalizado}"
                                       style="font-weight: bold;"
                                       decimalSeparator="," thousandSeparator="."
                                       onkeypress="if (event.keyCode == 13) { return false; }"/>

                        <h:panelGroup class="input-group">
                            <p:inputNumber id="valorProvavelPedido" value="#{cadastroProcessoController.pedidoSelecionado.valorProvavel}"
                                           disabled="#{cadastroProcessoController.processo.processoFinalizado}"
                                           style="font-weight: bold;"
                                           decimalSeparator="," thousandSeparator="."
                                           onkeypress="if (event.keyCode == 13) { return false; }"/>
                            <span class="input-group-btn">
                               <h:commandLink class="btn btn-success"
                                              actionListener="#{cadastroProcessoController.adicionarPedido}"
                                              disabled="#{cadastroProcessoController.processo.processoFinalizado}"
                                              title="#{cadastroProcessoController.processo.processoFinalizado ? bundleMsgs.bt_processo_finalizado : bundleMsgs.bt_adicionar}"
                                              style="width: 45px; height: 34px; color: #fff !important;">
                                   <span class="fa fa-plus"></span>
                                   <p:ajax process="valoresFormGroup" update="pedidosTable valoresFormGroup @parent" />
                               </h:commandLink>
                            </span>
                        </h:panelGroup>
                    </p:panelGrid>

                    <p:spacer height="15"/>

                    <p:outputPanel id="pedidos">
                        <p:dataTable value="#{cadastroProcessoController.processo.pedidos}" var="row" id="pedidosTable" emptyMessage="#{bundleMsgs.empty_results}">
                            <p:column headerText="#{bundleMsgs.label_pedido}">
                                <h:outputText value="#{row.pedido.descricao}" />
                            </p:column>

                            <p:column headerText="#{bundleMsgs.label_causa_pedido}">
                                <h:outputText value="#{row.causaPedido.descricao}" />
                            </p:column>

                            <p:column headerText="#{bundleMsgs.label_valor_pedido}" style="text-align: center;">
                                <h:outputText value="#{row.valorPedido}" >
                                    <f:convertNumber type="currency" currencySymbol="R$" />
                                </h:outputText>
                            </p:column>

                            <p:column headerText="#{bundleMsgs.label_valor_provavel}" style="text-align: center;">
                                <h:outputText value="#{row.valorProvavel}" >
                                    <f:convertNumber type="currency" currencySymbol="R$" />
                                </h:outputText>
                            </p:column>

                            <p:column style="width: 6%;">
                                <p:commandLink class="btn btn-danger btn-sm" update="@form" process="@form" style="color: #fff !important;"
                                               disabled="#{cadastroProcessoController.processo.processoFinalizado}"
                                               title="#{cadastroProcessoController.processo.processoFinalizado ? bundleMsgs.bt_processo_finalizado : ''}">
                                    <span class="fa fa-trash-o"></span>
                                    <p:collector value="#{row}" removeFrom="#{cadastroProcessoController.processo.pedidos}" unique="true"/>
                                </p:commandLink>
                            </p:column>
                        </p:dataTable>
                    </p:outputPanel>
                </p:panel>
            </div>
        </div>
        <div class="row">
            <h:panelGroup id="grauRiscoGroup">
                <div class="col-md-3 col-xs-12 form-group">
                    <h4>#{bundleMsgs.label_grau_risco} *</h4>


                    <h:panelGroup id="inputGroupGrauRisco" class="input-group">
                        <h:selectOneMenu
                                value="#{cadastroProcessoController.processo.grauRisco}"
                                disabled="#{cadastroProcessoController.processo.processoFinalizado}"
                                styleClass="form-control select2" converter="entityConverter">
                            <f:selectItem itemLabel="" itemValue="#{null}" />
                            <f:selectItems var="grau" value="#{processoListasController.grausRisco}" itemLabel="#{grau.descricao}" />
                            <f:ajax event="change" execute="grauRiscoGroup" />
                        </h:selectOneMenu>
                        <span class="input-group-btn">
                                <h:commandLink class="btn btn-input"
                                               rendered="#{grauRiscoController.hasAccess}"
                                               title="#{cadastroProcessoController.processo.processoFinalizado ? bundleMsgs.bt_processo_finalizado : bundleMsgs.bt_adicionar}"
                                               disabled="#{cadastroProcessoController.processo.processoFinalizado}">
                                    <i class="fa fa-plus"></i>
                                    <p:ajax process="@this" listener="#{cadastroProcessoController.abrirGrauRiscoListener()}"  />
                                </h:commandLink>
                            </span>
                    </h:panelGroup>
                </div>
            </h:panelGroup>

            <div class="col-md-3 col-xs-12 form-group">
                <h4>#{bundleMsgs.label_valor_causa} *</h4>
                <p:inputNumber id="edtValorCausa" value="#{cadastroProcessoController.processo.valorCausa}"
                               disabled="#{cadastroProcessoController.processo.processoFinalizado}"
                               style="font-weight: bold;"
                               decimalSeparator="," thousandSeparator="."
                               onkeypress="if (event.keyCode == 13) { return false; }">
                    <p:ajax event="blur" update="edtValorCausa valoresFormGroup" />
                </p:inputNumber>
            </div>

            <div class="col-md-3 col-xs-12 form-group">
                <h4>#{bundleMsgs.label_valor_total_provavel}</h4>
                <h:inputText id="edtValorTotalProvavel" disabled="true"
                             pt:data-mask="decimal" converter="javax.faces.BigDecimal"
                             class="form-control"
                             value="#{cadastroProcessoController.processo.totalValorProvavel}">
                    <f:convertNumber maxFractionDigits="2" minFractionDigits="2" type="number" />
                </h:inputText>
            </div>

            <div class="col-md-3 col-xs-12 form-group">
                <h4>#{bundleMsgs.label_valor_total_pedido}</h4>
                <p:inputText id="edtValorTotalPedido" disabled="true"
                             pt:data-mask="decimal" converter="javax.faces.BigDecimal"
                             class="form-control"
                             value="#{cadastroProcessoController.processo.totalValorPedido}">
                    <f:convertNumber maxFractionDigits="2" minFractionDigits="2" type="number" />
                </p:inputText>
            </div>
        </div>
    </h:panelGroup>
</ui:composition>