web-juridico-webapp/src/main/java/br/com/juridico/controller/EmailController.java
package br.com.juridico.controller;

import br.com.juridico.business.ParametroEmailBusiness;
import br.com.juridico.datamodel.LazyEntityDataModel;
import br.com.juridico.entidades.Direito;
import br.com.juridico.entidades.Email;
import br.com.juridico.entidades.EmailVinculoParametro;
import br.com.juridico.entidades.ParametroEmail;
import br.com.juridico.exception.CrudException;
import br.com.juridico.exception.ValidationException;
import br.com.juridico.filter.ConsultaLazyFilter;
import br.com.juridico.impl.DireitoSessionBean;
import br.com.juridico.impl.EmailSessionBean;
import br.com.juridico.impl.ParametroEmailSessionBean;
import br.com.juridico.impl.PerfilAcessoSessionBean;
import br.com.juridico.types.EmailStepsTypes;
import com.google.common.base.Strings;
import com.google.common.collect.Lists;
import org.primefaces.model.LazyDataModel;

import javax.annotation.PostConstruct;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import java.util.List;

/**
 * Created by jeffersonl2009_00 on 27/06/2016.
 */
@Named
@ViewScoped
public class EmailController extends CrudController<Email> {

    private static final String EMAIL_FORM = "emailForm";
    private static final String CHAVE_ACESSO = "EMAIL_EMAIL_TEMPLATE";
    private static final String PAGINA_FORMULARIO = "/pages/cadastros/email/email-template.xhtml?faces-redirect=true";
    private static final String AGENDA = "AGENDA";
    private static final String SENHA = "SENHA";
    private static final String PROCESSO = "PROC";

    private static final String[] STEP_TYPES = {"STEP_CONFIGURACAO", "STEP_EMAIL"};

    @Inject
    private EmailSessionBean emailSessionBean;
    @Inject
    private PerfilAcessoSessionBean perfilAcessoSessionBean;
    @Inject
    private DireitoSessionBean direitoSessionBean;
    @Inject
    private ParametroEmailSessionBean parametroEmailSessionBean;

    private  List<ParametroEmail> parametroEmailsPessoa = Lists.newArrayList();
    private  List<ParametroEmail> parametroEmailsProcesso = Lists.newArrayList();
    private  List<ParametroEmail> parametroEmailsAgenda = Lists.newArrayList();

    private String tipoEmailSelecionado;
    private String editorText;
    private EmailStepsTypes stepsTypesSelecionado;
    private String stepClick;

    @PostConstruct
    private void initialize(){
        this.initWizardConfiguracao();
        getObjetoSelecionado().setDescricao(null);
        LazyDataModel<Email> listFlash = (LazyDataModel<Email>) getFlashScope().get(LIST_FLASH);

        if(listFlash != null) {
            setLazyDataModel(listFlash);
            return;
        }
        super.buscarPorLazy();
    }

    protected void initWizardConfiguracao() {
        this.stepsTypesSelecionado = EmailStepsTypes.STEP_CONFIGURACAO;
        this.stepClick = stepsTypesSelecionado.getValue();
        this.getObjetoSelecionado().setDescricao(null);
    }

    @Override
    protected void aposCancelar() throws CrudException {
        getObjetoSelecionado().setDescricao(null);
        updateContext(EMAIL_FORM);
        super.aposCancelar();
    }

    @Override
    protected void carregaLazyDataModel() {
        setLazyDataModel(new LazyEntityDataModel<Email>() {
            @Override
            protected List<Email> consultaFiltrada(ConsultaLazyFilter filtro) {
                filtro.setDescricao(getDescricaoFiltro());
                filtro.setCodigoEmpresa(getStateManager().getEmpresaSelecionada().getId());
                filtro.setPossuiExclusaoLogica(false);
                return emailSessionBean.filtrados(filtro);
            }

            @Override
            protected int countTotalRegistros(ConsultaLazyFilter filtro) {
                filtro.setCodigoEmpresa(getStateManager().getEmpresaSelecionada().getId());
                filtro.setPossuiExclusaoLogica(false);
                return emailSessionBean.quantidadeFiltrados(filtro);
            }
        });
    }

    public void returnToConfiguracao() {
        initWizardConfiguracao();
        emailSessionBean.clearSession();
        updateContext(EMAIL_FORM);
    }

    public List<Email> getEmails() {
        return emailSessionBean.retrieveAll(getStateManager().getEmpresaSelecionada().getId());
    }

    @Override
    protected void create(Email email) throws ValidationException, CrudException {
        atualizarParametroNaTabelaVinculo(email);
        emailSessionBean.update(email);
    }

    private void atualizarParametroNaTabelaVinculo(Email email) {
        if(Strings.isNullOrEmpty(email.getDescricao())) {
            return;
        }

        getObjetoSelecionado().getParametroEmails().clear();
        String[] parametros = ParametroEmailBusiness.retornaParametrosDoTexto(email.getDescricao());
        if(parametros != null) {
            for (String parametro : parametros) {
                ParametroEmail parametroEmail = parametroEmailSessionBean.findBySigla(parametro);
                EmailVinculoParametro vinculoParametro = new EmailVinculoParametro(email, parametroEmail);
                getObjetoSelecionado().getParametroEmails().add(vinculoParametro);
            }
        }
    }

    @Override
    public void salvar() {
        super.salvar();
        returnToConfiguracao();
    }

    @Override
    protected void antesDeSalvar() throws CrudException {
        if(!Strings.isNullOrEmpty(editorText)) {
            getObjetoSelecionado().setDescricao(editorText);
        }
    }

    @Override
    protected Email inicializaObjetosLazy(Email objeto) {
        emailSessionBean.clearSession();
        return emailSessionBean.retrieve(objeto.getId());
    }

    @Override
    protected Email instanciarObjetoNovo() {
        return new Email();
    }

    @Override
    protected void setEmpresaDeUsuarioLogado(Email objetoSelecionado) {
        objetoSelecionado.setCodigoEmpresa(getStateManager().getEmpresaSelecionada().getId());
    }

    private void initParametros() {
        this.parametroEmailsAgenda = parametroEmailSessionBean.findByGeralAndAgenda();
        this.parametroEmailsPessoa = parametroEmailSessionBean.findByGeralAndSenha();
        this.parametroEmailsProcesso = parametroEmailSessionBean.findByProcesso();
//        if(AGENDA.equals(tipoEmailSelecionado)) {
//            this.parametroEmailsAgenda = parametroEmailSessionBean.findByGeralAndAgenda();
//        } else if(SENHA.equals(tipoEmailSelecionado)) {
//            this.parametroEmailsPessoa = parametroEmailSessionBean.findByGeralAndSenha();
//        } else if(PROCESSO.equals(tipoEmailSelecionado)) {
//            this.parametroEmailsProcesso = parametroEmailSessionBean.findByProcesso();
//        }
    }

    public void stepNext() {
        switch (stepClick){
            case "STEP_CONFIGURACAO" :
                this.stepsTypesSelecionado = EmailStepsTypes.fromStep(STEP_TYPES[1]);
                this.stepClick = STEP_TYPES[1];
                break;
            default:
                this.stepsTypesSelecionado = EmailStepsTypes.fromStep(STEP_TYPES[0]);
                this.stepClick = STEP_TYPES[0];
        }
    }

    public void stepSelect(String step){
        if(Strings.isNullOrEmpty(step)){
            return;
        }
        this.stepClick = step;
    }

    /**
     *
     * @return
     */
    public String goToFormulario() {
        super.buscarPorLazy();
        getFlashScope().put(LIST_FLASH, getLazyDataModel());
        return PAGINA_FORMULARIO;
    }

    public void atualizaParametros(Email objeto) throws CrudException {
        if(objeto.getSigla().startsWith(AGENDA)) {
            tipoEmailSelecionado = AGENDA;
        } else if(objeto.getSigla().startsWith(SENHA)){
            tipoEmailSelecionado = SENHA;
        } else if(objeto.getSigla().startsWith(PROCESSO)){
            tipoEmailSelecionado = PROCESSO;
        }
        initParametros();
    }

    public List<ParametroEmail> getParametroEmailsPessoa() {
        return parametroEmailsPessoa;
    }

    public void setParametroEmailsPessoa(List<ParametroEmail> parametroEmailsPessoa) {
        this.parametroEmailsPessoa = parametroEmailsPessoa;
    }

    public List<ParametroEmail> getParametroEmailsProcesso() {
        return parametroEmailsProcesso;
    }

    public void setParametroEmailsProcesso(List<ParametroEmail> parametroEmailsProcesso) {
        this.parametroEmailsProcesso = parametroEmailsProcesso;
    }

    public List<ParametroEmail> getParametroEmailsAgenda() {
        return parametroEmailsAgenda;
    }

    public void setParametroEmailsAgenda(List<ParametroEmail> parametroEmailsAgenda) {
        this.parametroEmailsAgenda = parametroEmailsAgenda;
    }

    @Override
    protected void addChaveAcesso() {
        setChaveAcesso(CHAVE_ACESSO);
    }

    @Override
    protected boolean isPodeAlterar(){
        Direito direito = direitoSessionBean.retrieve(ALTERAR);
        return perfilAcessoSessionBean.possuiDireitoAcesso(getUser().getPerfil(), CHAVE_ACESSO, direito, getUser().getCodEmpresa());
    }

    @Override
    protected boolean isPodeExcluir(){
        Direito direito = direitoSessionBean.retrieve(EXCLUIR);
        return perfilAcessoSessionBean.possuiDireitoAcesso(getUser().getPerfil(), CHAVE_ACESSO, direito, getUser().getCodEmpresa());
    }

    @Override
    protected boolean isPodeIncluir(){
        Direito direito = direitoSessionBean.retrieve(INCLUIR);
        return perfilAcessoSessionBean.possuiDireitoAcesso(getUser().getPerfil(), CHAVE_ACESSO, direito, getUser().getCodEmpresa());
    }

    public String getEditorText() {
        return editorText;
    }

    public void setEditorText(String editorText) {
        this.editorText = editorText;
    }

    public EmailStepsTypes getStepsTypesSelecionado() {
        return stepsTypesSelecionado;
    }

    public String getStepClick() {
        return stepClick;
    }

}

web-juridico-webapp/src/main/webapp/pages/pessoas/pessoaJuridica/pessoa-juridica-list.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
      xmlns:stpro="http://java.sun.com/jsf/composite/stprocomponents">

<ui:composition template="../../../plain-template.xhtml">

    <!-- TITULO DA PAGINA -->
    <ui:define name="page-title">
        <div class="page-title">${bundleMsgs.pessoas}</div>
    </ui:define>

    <ui:define name="small-title">
        #{bundleMsgs.label_pessoa_juridica}
    </ui:define>

    <ui:define name="left_menu">
        <!-- ACTIVE MENU -->
        <ui:param name="active_home" value="" />
        <ui:param name="active_processos" value="" />
        <ui:param name="active_agenda" value="" />
        <ui:param name="active_cadastros" value="" />
        <ui:param name="active_contratos" value="" />
        <ui:param name="active_controladoria" value="" />
        <ui:param name="active_clientes" value="active" />
        <ui:param name="active_financeiro" value="" />
        <ui:param name="active_relatorios" value="" />
        <ui:param name="active_atendimento" value="" />
        <ui:param name="active_acessos" value="" />

        <!-- MENU LATERAL -->
        <ui:include src="../../../left-menu-template.xhtml" />
    </ui:define>

    <!-- BREADCRUMB -->
    <ui:define name="breadcrumb">
        <li><h:link outcome="/pages/index.xhtml">
            <i class="fa fa-home"></i>
            Home
        </h:link></li>
        <li class="active">${bundleMsgs.label_pessoa_juridica}</li>
    </ui:define>
    <!-- FIM DO BREADCRUMB -->

    <ui:define name="content">
        <h:form id="pessoaJuridicaListForm" prependId="false">

            <!-- Mensagens ******************************** -->
            <div class="row">
                <div class="col-xs-12 form-group">
                    <ui:include src="../../../_mensagens.xhtml" />
                </div>
            </div>
            <!-- Mensagens ................................ -->


            <section class="invoice">
                <div class="row">
                    <div class="col-xs-7 form-group" align="left">
                        <!--Inserir-->
                        <h:commandButton rendered="#{pessoaJuridicaController.permiteInclusao}"
                                         value="${bundleMsgs.bt_novo}" class="btn btn-success"
                                         action="#{pessoaJuridicaController.novaPessoaJuridica}">
                        </h:commandButton>
                    </div>

                    <div class="col-md-5 col-xs-12" align="right">
                        <div class="input-group">
                            <p:remoteCommand name="listFromSimpleSearch" update="dataTable"
                                             actionListener="#{pessoaJuridicaController.listFromSimpleSearch}"/>
                            <p:inputText value="#{pessoaJuridicaController.descricaoFiltro}"
                                         pt:autoFocus="true"
                                         pt:placeholder="${bundleMsgs.p_holder_buscar}"
                                         id="simpleSearchInput"
                                         onkeypress="if (event.keyCode == 13) { listFromSimpleSearch(); return false; }"
                                         title="#{simpleSearchPlaceholder}"/>

                        <span class="input-group-addon">
                            <h:commandLink id="btnSimpleFilter"
                                           action="#{pessoaJuridicaController.listFromSimpleSearch}"
                                           pt:data-loader="on"
                                           pt:data-loader-message="Pesquisando, Aguarde...">
                                <i class="fa fa-search"></i>
                            </h:commandLink>
                            <p:defaultCommand target="btnSimpleFilter"/>
						</span>

                        </div>
                    </div>
                </div>
            </section>

            <!--Listagem ********************************-->
            <div class="box">
                <div class="box-body">
                    <div class="table-responsive form-group">
                        <p:dataTable id="dataTable" var="row"
                                     emptyMessage="${bundleMsgs.empty_results}"
                                     rows="10" paginator="true" paginatorPosition="bottom"
                                     paginatorTemplate=" {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                                     rowsPerPageTemplate="5,10,15,50"
                                     value="#{pessoaJuridicaController.lazyDataModel}" lazy="true">

                            <p:column headerText="${bundleMsgs.label_nome}"
                                      sortBy="#{row.pessoa.descricao}">
                                <h:commandLink value="#{row.pessoa.descricao}" action="#{pessoaJuridicaController.goToDetalhes}"  >
                                    <f:setPropertyActionListener
                                            target="#{pessoaJuridicaController.pessoaJuridicaSelecionada}"
                                            value="#{row}" />
                                </h:commandLink>                                
                            </p:column>

                            <p:column headerText="${bundleMsgs.label_responsavel}">
                                <h:outputText rendered="#{pessoaJuridicaController.podeVisualizarResponsaveis}" value="#{row.responsaveis}" />
                                <h:outputText rendered="#{!pessoaJuridicaController.podeVisualizarResponsaveis}" value="#{bundleMsgs.label_usuario_sem_permissao_visualizar_responsaveis}" />                                
                            </p:column>
                            
                            <p:column headerText="${bundleMsgs.label_email}">
                                <h:outputText rendered="#{pessoaJuridicaController.podeVisualizarEmails}" value="#{row.emails}" />
                                <h:outputText rendered="#{!pessoaJuridicaController.podeVisualizarEmails}" value="#{bundleMsgs.label_usuario_sem_permissao_visualizar_emails}" />
                            </p:column>

                            <p:column headerText="${bundleMsgs.label_telefone}">
                                <h:outputText rendered="#{pessoaJuridicaController.podeVisualizarContatos}" value="#{row.telefones}" />
                                <h:outputText rendered="#{!pessoaJuridicaController.podeVisualizarContatos}" value="#{bundleMsgs.label_usuario_sem_permissao_visualizar_contatos}" />                                
                            </p:column>

                            <p:column style="text-align: center; width: 150px">
                                <h:commandLink id="btnDetalhes" rendered="#{true}"
                                               class="btn btn-info btn-sm"
                                               style="color: #fff !important;"
                                               action="#{pessoaJuridicaController.goToDetalhes()}"
                                               title="${bundleMsgs.bt_detalhes}">
                                    <span class="fa fa-file-text-o"></span>
                                    <f:setPropertyActionListener
                                            target="#{pessoaJuridicaController.pessoaJuridicaSelecionada}"
                                            value="#{row}" />
                                </h:commandLink>
                                <p:spacer width="3" />
                                <h:commandLink id="btnEditar" rendered="#{pessoaJuridicaController.permiteAlteracao}" 
                                               class="btn btn-warning btn-sm" style="color: #fff !important;"
                                               title="${bundleMsgs.bt_editar}"
                                               action="#{pessoaJuridicaController.goToEditarPessoa(row)}">
                                    <span class="fa fa-pencil"></span>
                                </h:commandLink>
                                <p:spacer width="3" />
                                <h:commandLink id="btnExcluir" rendered="#{pessoaJuridicaController.permiteExclusao}"
                                               class="btn btn-danger btn-sm" style="color: #fff !important;"
                                               title="${bundleMsgs.bt_excluir}">
                                    <span class="fa fa-trash-o"></span>
                                    <f:setPropertyActionListener
                                            target="#{pessoaJuridicaController.objetoSelecionado}"
                                            value="#{row}"></f:setPropertyActionListener>
                                    <f:ajax onevent="openModal('#myModal')" />
                                </h:commandLink>
                            </p:column>
                        </p:dataTable>
                    </div>
                </div>
            </div>

            <!-- COMPONENTE POPUP -->
            <stpro:exclusion-popup controller="#{pessoaJuridicaController}" />

            <h:panelGroup>
                <ui:include src="../../popups/pessoa-juridica-popup.xhtml" />
            </h:panelGroup>
        </h:form>
    </ui:define>
</ui:composition>
</html>