web-juridico-webapp/src/main/java/br/com/juridico/controller/manutencao/ManutencaoAcessoController.java
package br.com.juridico.controller.manutencao;

import br.com.juridico.controller.CrudController;
import br.com.juridico.entidades.Acesso;
import br.com.juridico.entidades.Menu;
import br.com.juridico.exception.CrudException;
import br.com.juridico.exception.ValidationException;
import br.com.juridico.impl.AcessoSessionBean;
import br.com.juridico.impl.MenuSessionBean;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.inject.Inject;
import java.util.List;

/**
 * Created by jefferson on 22/10/2016.
 */
@ManagedBean
@ViewScoped
public class ManutencaoAcessoController extends CrudController<Acesso> {

    @Inject
    private AcessoSessionBean acessoSessionBean;
    @Inject
    private MenuSessionBean menuSessionBean;


    public List<Acesso> getAcessos() {
        return acessoSessionBean.findAcessosDoSistema();
    }

    public List<Menu> getMenus(){
        return menuSessionBean.findAllMenus();
    }

    @Override
    protected void aposCancelar() throws CrudException {
        getObjetoSelecionado().setFuncionalidade(null);
        updateContext("form");
        super.aposCancelar();
    }

    @Override
    protected void create(Acesso acesso) throws ValidationException, CrudException {
        if (isEditavel()) {
            acessoSessionBean.update(acesso);
            return;
        }
        acessoSessionBean.create(acesso);
    }

    @Override
    protected void carregaLazyDataModel() {
        // carregaLazyDataModel
    }

    @Override
    protected Acesso inicializaObjetosLazy(Acesso objetoSelecionado) {
        acessoSessionBean.clearSession();
        return acessoSessionBean.retrieve(objetoSelecionado.getId());
    }

    @Override
    protected Acesso instanciarObjetoNovo() {
        return new Acesso();
    }

    @Override
    protected void setEmpresaDeUsuarioLogado(Acesso objetoSelecionado) {
        // setEmpresaDeUsuarioLogado
    }

    @Override
    protected void addChaveAcesso() {
        // addChaveAcesso
    }

    @Override
    protected boolean isPodeAlterar() {
        return false;
    }

    @Override
    protected boolean isPodeExcluir() {
        return false;
    }

    @Override
    protected boolean isPodeIncluir() {
        return false;
    }
}

web-juridico-webapp/src/main/java/br/com/juridico/controller/manutencao/ManutencaoConfiguracaoController.java
package br.com.juridico.controller.manutencao;

import br.com.juridico.controller.AbstractController;
import br.com.juridico.entidades.Configuracao;
import br.com.juridico.entidades.Empresa;
import br.com.juridico.entidades.EmpresaConfiguracao;
import br.com.juridico.exception.ValidationException;
import br.com.juridico.impl.ConfiguracaoSessionBean;
import br.com.juridico.impl.EmpresaConfiguracaoSessionBean;
import br.com.juridico.impl.EmpresaSessionBean;
import br.com.juridico.impl.PessoaSessionBean;
import org.apache.log4j.Logger;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.inject.Inject;
import java.util.Iterator;
import java.util.List;

/**
 * Created by Marcos Melo on 10/01/2017.
 */
@ManagedBean
@ViewScoped
public class ManutencaoConfiguracaoController extends AbstractController {

    private static final Logger LOGGER = Logger.getLogger(ManutencaoConfiguracaoController.class);

    @Inject
    private PessoaSessionBean pessoaSessionBean;
    @Inject
    private EmpresaConfiguracaoSessionBean empresaConfiguracaoSessionBean;
    @Inject
    private ConfiguracaoSessionBean configuracaoSessionBean;
    @Inject
    private EmpresaSessionBean empresaSessionBean;

    @PostConstruct
    public void initialize(){
        empresaSessionBean.clearSession();
    }

    public void atualizaModuloAtivo(Empresa empresa, String configuracao) {
        empresaSessionBean.clearSession();
        Configuracao conf = configuracaoSessionBean.findByDescricao(configuracao);
        EmpresaConfiguracao empresaConfiguracao = empresaConfiguracaoSessionBean.findByEmpresaAndConfiguracao(empresa.getId(), conf.getId());

        try {
            if (empresaConfiguracao != null) {
                for (Iterator<EmpresaConfiguracao> iterator = empresa.getConfiguracoes().iterator(); iterator.hasNext();) {
                    EmpresaConfiguracao empresaConf = iterator.next();
                    if (empresaConfiguracao.equals(empresaConf)) {
                        iterator.remove();
                    }
                }
                empresaSessionBean.update(empresa);
                return;
            }
            EmpresaConfiguracao novaConfiguracao = new EmpresaConfiguracao(empresa, conf);
            empresaConfiguracaoSessionBean.create(novaConfiguracao);
        } catch (ValidationException e) {
            LOGGER.error(e, e.getCause());
        }
    }

    public List<Empresa> getEmpresas(){
        return empresaSessionBean.findAllEmpresas();
    }
}

web-juridico-webapp/src/main/java/br/com/juridico/controller/manutencao/ManutencaoEmpresaController.java
package br.com.juridico.controller.manutencao;

import br.com.juridico.controller.CrudController;
import br.com.juridico.dto.PerfilAcessoDto;
import br.com.juridico.entidades.*;
import br.com.juridico.enums.EmailIndicador;
import br.com.juridico.enums.MenuIndicador;
import br.com.juridico.exception.CrudException;
import br.com.juridico.exception.ValidationException;
import br.com.juridico.impl.*;
import br.com.juridico.mail.MailBusiness;
import br.com.juridico.util.DecryptUtil;
import br.com.juridico.util.EncryptUtil;
import br.com.juridico.util.FileUtil;
import br.com.juridico.util.Util;
import com.google.common.base.Strings;
import com.google.common.collect.Lists;
import org.apache.commons.io.IOUtils;
import org.apache.log4j.Logger;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.event.ValueChangeEvent;
import javax.inject.Inject;
import javax.mail.MessagingException;
import javax.servlet.http.Part;
import java.io.IOException;
import java.util.Date;
import java.util.List;

/**
 * Created by jefferson on 22/10/2016.
 */
@ManagedBean
@ViewScoped
public class ManutencaoEmpresaController extends CrudController<Empresa> {

    private static final Logger LOGGER = Logger.getLogger(ManutencaoEmpresaController.class);
    private static final String BLOCK = "BLOCK";
    public static final String EMAIL_DESTINATARIO = "EMAIL_DESTINATARIO";
    public static final String TEMPO_CONSULTA_EMAIL = "TEMPO_CONSULTA_EMAIL";
    public static final Character PESSOA_FISICA = 'F';
    public static final String ADMIN = "ADMIN";
    public static final String CLIENTE = "CLIENTE";


    @Inject
    private EmpresaSessionBean empresaSessionBean;
    @Inject
    private ImagemSessionBean imagemSessionBean;
    @Inject
    private PerfilSessionBean perfilSessionBean;
    @Inject
    private ParametroSessionBean parametroSessionBean;
    @Inject
    private PosicaoSessionBean posicaoSessionBean;
    @Inject
    private UfSessionBean ufSessionBean;
    @Inject
    private PessoaFisicaSessionBean pessoaFisicaSessionBean;
    @Inject
    private AcessoSessionBean acessoSessionBean;
    @Inject
    private PerfilAcessoSessionBean perfilAcessoSessionBean;
    @Inject
    private DireitoPerfilSessionBean direitoPerfilSessionBean;
    @Inject
    private PessoaConfiguracaoSessionBean pessoaConfiguracaoSessionBean;
    @Inject
    private DireitoSessionBean direitoSessionBean;
    @Inject
    private StatusAgendaSessionBean statusAgendaSessionBean;
    @Inject
    private TipoAndamentoSessionBean tipoAndamentoSessionBean;
    @Inject
    private EmailSessionBean emailSessionBean;


    private Imagem imagem;
    private Part arquivo;
    private String liberacao;
    private boolean novaEmpresaSelected;
    private PessoaFisica pessoaFisica;
    private List<Uf> ufs;
    private String confEmail;
    private boolean empresaMatriz = Boolean.TRUE;

    @PostConstruct
    public void initialize(){
        initImagem();
        this.setUfs(ufSessionBean.findAll());
        this.pessoaFisica = new PessoaFisica();
        this.pessoaFisica.setPessoa(new Pessoa());
    }

    private void initImagem() {
        this.imagem = new Imagem();
    }

    public List<Empresa> getEmpresas(){
        return empresaSessionBean.findAllEmpresas();
    }

    @Override
    protected void aposCancelar() throws CrudException {
        getObjetoSelecionado().setDescricao(null);
        initImagem();
        updateContext("form");
        super.aposCancelar();
    }

    @Override
    protected void antesDeSalvar() throws CrudException {
        try {
            getObjetoSelecionado().setDataCadastro(new Date());
            if(!Strings.isNullOrEmpty(liberacao)){
                getObjetoSelecionado().setLiberacao(EncryptUtil.execute(liberacao));
            }
        } catch (Exception e) {
            LOGGER.error(e, e.getCause());
        }
    }

    @Override
    protected void create(Empresa empresa) throws ValidationException, CrudException {
        if (isEditavel()) {
            empresaSessionBean.update(empresa);
            return;
        }
        empresaSessionBean.create(empresa);
    }

    @Override
    protected void carregaLazyDataModel() {
        // carregaLazyDataModel
    }

    public void buscaImagemEmpresa(){
        if(getUser() == null){
            return;
        }
        Empresa empresa = empresaSessionBean.retrieve(getUser().getCodEmpresa());
        this.imagem = empresa.getImagem();
    }

    @Override
    protected Empresa inicializaObjetosLazy(Empresa objetoSelecionado) {
        empresaSessionBean.clearSession();
        return empresaSessionBean.retrieve(objetoSelecionado.getId());
    }

    @Override
    protected Empresa instanciarObjetoNovo() {
        return new Empresa();
    }



    @Override
    protected void antesDeEditar(Empresa objeto) throws CrudException {
        if(objeto.getImagem() != null) {
            this.imagem = objeto.getImagem();
        }
        try {
            setLiberacao(DecryptUtil.execute(getObjetoSelecionado().getLiberacao()));
        } catch (Exception e) {
            LOGGER.error(e, e.getCause());
        }
    }

    public void importar() {
        try {
            byte[] bytes = IOUtils.toByteArray(arquivo.getInputStream());
            String nomeArquivo = FileUtil.getFileName(arquivo);
            String extensao = nomeArquivo.substring(nomeArquivo.lastIndexOf("."), nomeArquivo.length());

            if(this.imagem.getId() == null) {
                this.imagem = new Imagem(bytes, nomeArquivo, extensao);
                imagemSessionBean.create(imagem);
                getObjetoSelecionado().setImagem(this.imagem);
            } else {
                this.imagem.setLogo(bytes);
                this.imagem.setNomeArquivo(nomeArquivo);
                this.imagem.setExtensaoArquivo(extensao);
                imagemSessionBean.update(imagem);
                getObjetoSelecionado().setImagem(this.imagem);

            }
        } catch (IOException e) {
            LOGGER.error(e, e.getCause());
        } catch (ValidationException e) {
            LOGGER.error(e, e.getCause());
        }
    }

    @Override
    protected void validar() throws ValidationException {

    }

    public String salvarNovoEmpresa(){
        try {
            antesDeSalvar();
            getObjetoSelecionado().validar();
            empresaSessionBean.create(getObjetoSelecionado());
            salvarStatusAgenda();
            salvarTipoAndamento();
            salvarPerfis();
            salvarParametros();
            salvarPosicao();
            salvarEmails();
            salvarPessoa();
            adicionaLoginSenha();
            pessoaFisicaSessionBean.update(this.pessoaFisica);
            adicionarAcessos();
            salvarConfiguracaoEmail();
            enviaEmailNovoUsuarioPessoa();
            getEmpresas();
            exibirMensagem(FacesMessage.SEVERITY_INFO, getMessage("msg_sucesso_salvar"));
            return goToEmpresas();

        } catch (ValidationException e) {
            for (String message : e.getMessages()) {
                exibirMensagem(FacesMessage.SEVERITY_ERROR, message);
            }
            return "";
        } catch (CrudException e) {
            LOGGER.error(e, e.getCause());
            return "";
        } catch (Exception e) {
            LOGGER.error(e, e.getCause());
            return "";
        }
    }

    private void salvarConfiguracaoEmail() throws ValidationException {
        ConfiguracaoEmail configuracaoEmail = new ConfiguracaoEmail(
                "mail.stpro.com.br",
                587,
                "naoresponda@stpro.com.br",
                "advogados2016",
                "SMTP",
                this.getConfEmail(),
                getObjetoSelecionado().getId());

        getObjetoSelecionado().setConfiguracaoEmail(configuracaoEmail);
    }

    private void salvarStatusAgenda() throws ValidationException {
        statusAgendaSessionBean.create(new StatusAgenda("Cumprido", "event-text-color-lightSlateGray", Boolean.FALSE, getObjetoSelecionado().getId()));
        statusAgendaSessionBean.create(new StatusAgenda("À cumprir", "event-text-color-green", Boolean.FALSE, getObjetoSelecionado().getId()));
        statusAgendaSessionBean.create(new StatusAgenda("Cancelado", "event-text-color-red", Boolean.FALSE, getObjetoSelecionado().getId()));
        statusAgendaSessionBean.create(new StatusAgenda("Rejeitado", "event-text-color-orange", Boolean.FALSE, getObjetoSelecionado().getId()));
    }

    private void salvarTipoAndamento() throws ValidationException {
        TipoAndamento tipoAudienciaConciliacao = new TipoAndamento("Audiência de Conciliação", Boolean.TRUE, 0L, getObjetoSelecionado().getId());
        TipoAndamento tipoAudienciaOitiva = new TipoAndamento("Audiência Oitiva", Boolean.TRUE, 0L, getObjetoSelecionado().getId());
        TipoAndamento tipoAudienciaInstrucao = new TipoAndamento("Audiência de Instrução", Boolean.TRUE, 0L, getObjetoSelecionado().getId());

        tipoAndamentoSessionBean.create(tipoAudienciaConciliacao);
        tipoAndamentoSessionBean.create(tipoAudienciaOitiva);
        tipoAndamentoSessionBean.create(tipoAudienciaInstrucao);
    }

    private void salvarEmails() throws ValidationException {
        emailSessionBean.create(new Email("SENHA_RECUPERACAO_SENHA", "Recuperar senha", ".", getObjetoSelecionado().getId(), Boolean.TRUE, Boolean.TRUE));
        emailSessionBean.create(new Email("SENHA_ALTERACAO_SENHA", "Alteração de senha", ".", getObjetoSelecionado().getId(), Boolean.TRUE, Boolean.TRUE));
        emailSessionBean.create(new Email("SENHA_NOVO_USUARIO", "Novo Usuário", ".", getObjetoSelecionado().getId(), Boolean.TRUE, Boolean.TRUE));

web-juridico-webapp/src/main/webapp/manutencao/senhausuario/manutencao-senhausuario-list.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
      xmlns:f="http://java.sun.com/jsf/core">


<!--Titulo da Tela..............................-->
<div class="row">
    <div class="form-group col-xs-12">
        <h3 class="box-title">Registros</h3>
    </div>
</div>
<!--Titulo da Tela*******************************-->


<!--Listagem ********************************-->
<div class="box">
    <div class="box-body">
        <div class="table-responsive form-group">

            <div class="col-md-3 col-xs-12 form-group">
                <h:outputLabel value="#{bundleMsgs.label_empresa} *"
                               class="simple-label" />
                <h:selectOneMenu value="#{manutencaoSenhaUsuarioController.empresaSelecionada}"
                                 styleClass="form-control select2"
                                 converter="entityConverter">
                    <f:selectItem itemLabel="" itemValue="#{null}"/>
                    <f:selectItems var="e" value="#{manutencaoSenhaUsuarioController.empresas}"
                                   itemLabel="#{e.descricao}" />
                    <p:ajax event="change" process="@this" oncomplete="setConfirmUnload(true)"
                            listener="#{manutencaoSenhaUsuarioController.carregaPessoas}" update="@form"/>
                </h:selectOneMenu>
            </div>

            <h:panelGroup id="buscaGroup" rendered="#{manutencaoSenhaUsuarioController.empresaSelecionada.id ne null}">
                <div class="col-md-4 col-xs-12 form-group">
                    <h:outputLabel value="% nome %" class="simple-label" />

                    <div class="input-group">
                        <p:remoteCommand name="listFromSimpleSearch" update="datatable" actionListener="#{manutencaoSenhaUsuarioController.listFromSimpleSearch}"/>
                        <p:inputText value="#{manutencaoSenhaUsuarioController.buscaRapida}"
                                     pt:autoFocus="true"
                                     pt:placeholder="${bundleMsgs.p_holder_buscar}"
                                     id="simpleSearchInput"
                                     onkeypress="if (event.keyCode == 13) { listFromSimpleSearch(); return false; }"
                                     title="#{simpleSearchPlaceholder}">
                            <f:ajax event="change" listener="#{manutencaoSenhaUsuarioController.listFromSimpleSearch}" />
                        </p:inputText>

                        <span class="input-group-addon">
                            <h:commandLink id="btnSimpleFilter"
                                           pt:data-loader="on"
                                           pt:data-loader-message="Pesquisando, Aguarde..."
                                           onclick="setConfirmUnload(false)"
                                           action="#{manutencaoSenhaUsuarioController.listFromSimpleSearch}">
                                <i class="fa fa-search"></i>
                            </h:commandLink>
                            <p:defaultCommand target="btnSimpleFilter" />
                        </span>
                    </div>
                </div>
            </h:panelGroup>

            <div class="col-md-12 col-xs-12 form-group">
                <p:dataTable id="datatable" var="row" value="#{manutencaoSenhaUsuarioController.senhaPessoas}"
                             rows="10" paginator="true" paginatorPosition="bottom"
                             paginatorTemplate=" {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                             rowsPerPageTemplate="5,10,15,50" emptyMessage="#{bundleMsgs.msg_nenhum_registro}" >

                    <p:column headerText="${bundleMsgs.label_nome}" sortBy="#{row.nome}" >
                        <h:outputText value="#{row.nome}" />
                    </p:column>

                    <p:column headerText="${bundleMsgs.label_login}" sortBy="#{row.login}" >
                        <h:outputText value="#{row.login}" />
                    </p:column>

                    <p:column headerText="${bundleMsgs.label_senha}" sortBy="#{row.senha}" >
                        <h:outputText value="#{row.senha}" />
                    </p:column>

                    <p:column headerText="${bundleMsgs.label_data_ultimo_acesso}" sortBy="#{row.dataUltimoAcesso}" >
                        <h:outputText value="#{row.dataUltimoAcesso}" >
                            <f:convertDateTime pattern="dd/MM/yyyy HH:mm:ss" />
                        </h:outputText>
                    </p:column>

                    <p:column headerText="Primeiro Acesso" style="width: 15%; text-align: center;">
                        <h:outputText value="#{row.primeiroAcesso ? 'SIM' : 'NAO'}" />
                    </p:column>
                </p:dataTable>
            </div>
        </div>
    </div>
</div>
</html>

web-juridico-webapp/src/main/webapp/manutencao/senhausuario/manutencao-senhausuario-template.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:stpro="http://java.sun.com/jsf/composite/stprocomponents">

<ui:composition template="../../plain-manutencao-template.xhtml">

	<!-- TITULO DA PAGINA -->
	<ui:define name="page-title">
		<div class="page-title">Senha Usuario</div>
	</ui:define>

	<!-- BREADCRUMB -->
	<ui:define name="breadcrumb">
		<li><h:link outcome="/manutencao/manutencao-template.xhtml" onclick="setConfirmUnload(false)">
			<i class="fa fa-home" /> Manutenção
		</h:link></li>
		<li class="active">Senha Usuario</li>
	</ui:define>
	<!-- FIM DO BREADCRUMB -->

	<ui:define name="content">
		<h:form id="form" prependId="false">

			<!-- Mensagens ******************************** -->
			<div class="row">
				<div class="col-xs-12 form-group">
					<ui:include src="../../_mensagens.xhtml" />
				</div>
			</div>
			<!-- Mensagens ................................ -->

			<div class="row">
				<div class="box">
					<div class="box-header with-border">
						<div class="form-group">

							<!--Listagem *********************************-->
							<div class="col-sm-12 col-xs-12 form-group">
								<ui:include src="manutencao-senhausuario-list.xhtml" />
							</div>
							<!--Listagem .................................-->
						</div>
					</div>
				</div>
			</div>

            <!-- COMPONENTE POPUP -->
            <stpro:exclusion-popup controller="#{manutencaoSenhaUsuarioController}" />
		</h:form>
	</ui:define>
</ui:composition>
</html>